export const EVENTS = {
    // Client -> Server
    JOIN: 'JOIN',
    START_GAME: 'START_GAME',
    STOP_ROUND: 'STOP_ROUND',
    SUBMIT_ANSWERS: 'SUBMIT_ANSWERS',
    UPDATE_ANSWERS: 'UPDATE_ANSWERS',
    TOGGLE_VOTE: 'TOGGLE_VOTE',
    CONFIRM_VOTES: 'CONFIRM_VOTES',
    UPDATE_CONFIG: 'UPDATE_CONFIG',
    RESTART_GAME: 'RESTART_GAME',
    KICK_PLAYER: 'KICK_PLAYER',
    EXIT_GAME: 'EXIT_GAME',

    // Chat Events (Client -> Server)
    CHAT_SEND: 'CHAT_SEND',

    // Server -> Client
    UPDATE_STATE: 'UPDATE_STATE',
    RIVAL_UPDATE: 'RIVAL_UPDATE',
    SYSTEM_MESSAGE: 'SYSTEM',
    SYSTEM_VERSION: 'SYSTEM_VERSION',

    // Chat Events (Server -> Client)
    CHAT_NEW: 'CHAT_NEW',
    CHAT_HISTORY: 'CHAT_HISTORY'
} as const;

export const APP_VERSION = 'v0.5.0';

export const GAME_CONSTS = {
    MAX_POINTS: 100,
    HALF_POINTS: 50,
    ZERO_POINTS: 0,
    BONUS_POINTS: 10,

    DEFAULT_ROUND_DURATION: 60,
    DEFAULT_VOTING_DURATION: 45,
    DEFAULT_CATEGORIES_COUNT: 5,
    DEFAULT_TOTAL_ROUNDS: 5,

    MIN_CATEGORIES: 4,
    MAX_CATEGORIES: 8,

    MIN_ROUND_DURATION: 30,
    MAX_ROUND_DURATION: 180,

    MIN_VOTING_DURATION: 15,
    MAX_VOTING_DURATION: 120,

    ZOMBIE_TIMEOUT_MS: 15000
} as const;
